### ISSUE TITLE
Revamp how we handle committees

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1209]
We have multiple apps that needs to know what committee(s) a user is part of, so we need some way to figure out what (and/or which) committee(s) a user is in.

Some suggestions:
- permission class on committee groups, then find which groups have this permission (_hacky_)
- extend django.contrib Groups

**Comment by hernil** [comment]
#1308

**Comment by hernil** [comment]
I'd like anyone interested in modelling this to poke me so we can get a group working on this next week.

**Comment by myth** [comment]
Recap of the group discussion:

Since django does not support swappable group object out of the box, we should attempt to subclass Group and use it where we need, for example by using a custom manager.

An even better approach, at least in terms of functionality, is to set up our base group (see list of bullets below) by injecting common fields into the already existing Group object. Then django will add them to the same database table, removing one join operation from the equation. And we do really need to keep those in mind. A possible example of how this might be set up in models:

```
if not hasattr(Group, 'builtin'):
    setattr(Group, 'builtin', models.BooleanField('Gruppen er en innebygd gruppe eller tilknyttet kjernefunksjonalitet.')
```

The clear advantage of this compared to subclassing is the need to add another JOIN layer for our organizational entities, as well as laying the foundation for other future usages that depend on similar functionality.

Some bulletpoints from the discussion:

* Group description, short and long.
* Description should include the organizational entity's purpose and intent (from the reworked committee guidelines)
* A tree-like structure of organizational nodes, allowing inference of responsibility, ownership, informational aggregation, automatic organizational charts, automatically generated E-mail lists etc. Limitless possibilities.
* Remove all hacks with ints and strings in our code / settings
* A notion of parent and child branches (ref tree-like structure)
* Application for a group can be a generic group application form built upon the approvals app maybe? Automatic committee membership applications, prioritizing, application handling and statistics anyone?
* Fields for leader, second in command and possibly responsible for economy? An obvious solution would be an M2M field for unlimited roles/positions. We should keep the amount of M2M fields in consideration. 6-8 levels of joins are expensive. Hopefully it shouldn't be a big problem. Some benchmarking with 50-100 group objects with the proposed design would be nice.
* User-group-roles could allow automatic generation of "positions" on the user profile.
* User-group-roles could allow automatic reminders of who is up for "long and faithful service" medals, 3-year committee reapproval limit etc.
* And a plethora of other possibilities

**Comment by sklirg** [comment]
Would it be feasible to add Stripe keys as a field on the committee group model? Considering we have multiple committees with separate Stripe keys for separate accounts.

**Comment by myth** [comment]
It might, but then again it falls under the same category as with responsible for economy etc. It will not be relevant for the majority of group objects. It will surely be fine for now, but i assume more fields will come. It might be better off than adding another table just for generic key-value storage though.

Ideally this should be stored nowhere in the database, or in the repository.
It should be stored in the same location as other credentials we use, and customized as environment variables in the launch scripts for the application. But that is another discussion, related to #976 and the discussion regarding app settings registration we had on Slack a while back.

**Comment by hernil** [comment]
We should keep the possibility of having an "alumni" group function in mind when working on this as well.

**Comment by sklirg** [comment]
And we stumble across even more things we could annotate the m2m-relation with. I think we should look at through models once more before throwing them away.

**Comment by FredrikAugust** [comment]
RIP #1209.

**Comment by myth** [comment]
Awyiss.
