### ISSUE TITLE
The same AttendanceEvent status_codes is used multiple times

### ISSUE THREAD

**Issue by OptimusCrime** [dotKom/onlineweb4#1379]
Kind of defeats the porpupseoa012+

https://github.com/dotKom/onlineweb4/blob/develop/apps/events/models.py#L594
https://github.com/dotKom/onlineweb4/blob/develop/apps/events/models.py#L604
https://github.com/dotKom/onlineweb4/blob/develop/apps/events/models.py#L612

**Comment by sklirg** [comment]
Regarding your comment on the referenced issue (#1378), reworking the whole
template, we should make sure to follow the standards for status codes.
https://en.m.wikipedia.org/wiki/List_of_HTTP_status_codes

None of the current errors are server side errors, thus they should not be
5xx. 400 bad request is a nice catch-all. 403 permission denied works for a
couple of use cases. There won't be a status code for everything, so we
should probably also look at re-defining the existing ones and combine them
where that makes sense.

**Comment by OptimusCrime** [comment]
@sklirg : They are not HTTP status codes, they are just internal codes @melwil used to simplify the feedback. I dont think there is a HTTP code that signals "du har pikk og har fått utsatt påmelding i 24 timer". Also, we should not mess with the HTTP status codes that Django sends, as every page load is in fact a 200 Ok response. If we start returning 403, Google and others will act weird on us.

**Comment by myth** [comment]
Googlebot does not perform POST requests or any ajax shenanigans, so they can safely be used for that purpose. But ofc, a regular GET on the event should never return anything other than 200, unless it is a restricted event and the user is missing appropriate permissions.

**Comment by OptimusCrime** [comment]
We're talking about the event view, shich is a regular GET.

**Comment by sklirg** [comment]
My bad, I guessed they were HTTP status codes because they were 4xx and 5xx.

---

What are they used for? A quick search for 501 and 503 contains no results for anything other than the source code in `models.py`.

If they should still be included, I think they should be renamed as to not conflict with the HTTP status code name. Django HttpResponse already has `HttpResponse.status_code`, adding a `status_code` entry to the context dictionary is confusing.

---

Every _page load_ should be 200 OK, I agree. When we do ajax requests _on_ the page, thus not requesting a page, but rather some [async request](https://github.com/dotKom/onlineweb4/blob/6dea161fb6d1d70ba7dd203823456532355c46d8/apps/events/views.py#L70) returning some data, returning non-200 is perfectly fine.

**Comment by OptimusCrime** [comment]
No problem @sklirg, I guess @melwil implement it to differentiate different cases easier. Like you say, they are in fact not used, but could be used to do something in ajax requests or something, I don't know.

However, we can use these codes to solve #1378, because they are different results with the same error code (as of today), which there is no way of differentiate in the templates.

`status_code` may not be the best name for it, but it is not passed directly to the response or the context dict, they are under the `user_status` object, so `user_status.status_code` is the actual data entry.
