### ISSUE TITLE
Cannot register new user

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1398]
It's not possible to sign up a new user since the form does not supply the "saldo" value.

**Comment by sklirg** [comment]
The saldo-value should not be possible to be set by a user other than by interacting with the deposit/withdrawal functions, so there shouldn't be a field for it in the form.

Suggestions: 
- Override User creation method by hooking onto a `pre_save` signal and setting the field to its default value there (only on creation).
- Make the field nullable and set it the first time a user visits the shop (or deposits funds).
- Might be a bit late for this; Create a proxy model for handling user funds rather than adding it to the user authentication model.

**Comment by OptimusCrime** [comment]
Why cant this field be 0 by default?

**Comment by myth** [comment]
A field with a not-null constraint should always have a default value. Since this field is a balance, it should have a default of 0. It should also not be editable through any form. If in-fact an error has occurred and is confirmed by us, we, and only we should be able to alter the value of the balance (we are talking about real money, after all) by just using the shell or through a dotKom only-dashboard widget.

**Comment by sklirg** [comment]
Fixed in 2a565367f8ee423bb828c4b6539ec26619efe3ff.
