### ISSUE TITLE
Option to change year/grade in profile

### ISSUE THREAD

**Issue by signii** [dotkom/onlineweb4#1423]
Some students have courses from other education that they use to fill their (bachelor) degree. This will make them "bump up" a year or two. It should be possible to change this in your profile at OW. Today the option is to change the year you began to a year before. This will be wrong if you for example "bump up" in january, or if someone at some point want to use the year to something useful.

**Comment by melwil** [comment]
I approve of some way to let the users adjust this themselves, to some degree.

Should this be adjustable by the users themselves, or done by Hovedstyret as with any other application to field of study? If the users are allowed to change this themselves, it may undermine the whole class checking process of the event system in the first place?

**Comment by teatimes** [comment]
@melwil Is it a possibility to just add a "when are you finished" field with "spring 2017", "autumn 2018" etc in the application?

**Comment by henrikhorluck** [comment]
This will not be implemented, due to it conflicting with our limitation for e.g. events based on year, and ensuring people are the right year. A solution with out current setup is to either make an application to be set as the correct year through `profile/membership` or send an e-mail to Hovedstyret
