### ISSUE TITLE
New careeropportunity, nothing happens when clicking on calendar icon

### ISSUE THREAD

**Issue by Adrianht** [dotkom/onlineweb4#1907]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
To open the calendar so you can choose a date that the careeropportunity starts & ends.

## What is the current behaviour?
Nothing happens when clicking

## How do you reproduce this problem? 
Just click on the calendar icon

**Comment by sklirg** [comment]
Thanks for reporting this issue! I can reproduce it as well.

Steps to reproduce:

1) Go to /dashboard
2) Go to "Karrieremuligheter -> Legg til ny karrieremulighet"
3) Nothing happens if you click on the date field.

Open the developer console to see this error: `Uncaught TypeError: e(...).datetimepicker is not a function`

**Comment by FluidSense** [comment]
This bug affects all of the dashboard, I reproduced it by:

1. Go to /dashboard
2. Go to "Arrangement -> Opprett arrangement"
3. Nothing happens if you click on the date field.

**Comment by sklirg** [comment]
This was resolved in #1912 and is now released.
