### ISSUE TITLE
Styling blir borte i event beskrivelsen

### ISSUE THREAD

**Issue by monikahm** [dotkom/onlineweb4#1943]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
Lost styling. 

## What is the current behaviour?
Kommer uten styling som på bildet under.

## Other information

<img width="536" alt="skjermbilde 2017-11-01 kl 18 03 10" src="https://user-images.githubusercontent.com/31705349/32600092-b70f16e0-c53e-11e7-83da-cc66a21cd6b4.png">

**Comment by sklirg** [comment]
I think the main problem here is that all the styling is lost when this happens. It should look more like this (but with the correct information and any errors):

![image](https://user-images.githubusercontent.com/5422571/32601086-d695a9cc-c541-11e7-8f1a-cbc3c6a7378b.png)

**Comment by sardred** [comment]
:gb:

**Comment by sardred** [comment]
@monikahm have you been able to reproduce this bug, or should we close this issue until somebody points it out again?

**Comment by oleast** [comment]
Just thinking back, I might have come across this earlier.
The problem comes from when you load a view which is actually just a form?

[Example from dev](https://dev.online.ntnu.no/dashboard/events/613/create_attendance/)

I think I might have been redirected to one of those when I was editing something in Dashboard once
