### ISSUE TITLE
Broken date handling in careeropportunity display date

### ISSUE THREAD

**Issue by torjusti** [dotkom/onlineweb4#1973]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
A careeropportunity should be displayed from the start date.

## What is the current behaviour?
If the start date is in the past, but sufficiently close to the current date, the careeropportunity is not displayed. Setting the start date to an earlier date fixes the problem.

## How do you reproduce this problem? 

Set start date to the middle of the night the day before the current day.

**Comment by sklirg** [comment]
This has nothing to do with how much in the future the event is set.

The queryset attribute is evaluated when the process starts. If an opportunity object is set to start after the server evaluated the queryset, it won't make the cut, since `timezone.now()` was evaluated at the first execution and then stored.

A simple fix is to override the `get_queryset` method which will evaluate `timezone.now()` every time the request is run rather than the first time it is evaluated.
