### ISSUE TITLE
Unhandled JSON serialization of dict throwing errors 

### ISSUE THREAD

**Issue by FredrikAugust** [dotkom/onlineweb4#2119]
Afternoon everyone,

I have recently received an email from a certain _mister onlineweb4-prod_ who had a very exciting message for me, and I thought I should share its contents with you all, as you might find some of it interesting.

It appears that when adding attendees to an event, we serialize the data to JSON when responding:

```
LINE 382 IN FILE "./apps/events/dashboard/views.py:

return JsonResponse(event_ajax_handler(event, request))
```
Apparently, JSON doesn't like it when we serialize dictionaries, and therefore, tells us to pass a `safe` flag set to `False`.

Whether this is the correct approach for handling this, or if it should be reworked, I do not know, but I think we should look into it.

**Comment by sklirg** [comment]
Protip: You can link directly to a file and line number in GitHub:
https://github.com/dotkom/onlineweb4/blob/v4.24.38/apps/events/dashboard/views.py#L382

If you specify a commit or tag rather than develop/master branch, the line number will also be correct even after changes happen in the file. :-)

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-WW](https://sentry.io/organizations/dotkom/issues/1161916495/?referrer=github_plugin)
