### ISSUE TITLE
Nibble api silently succeeds it should fail.

### ISSUE THREAD

**Issue by Aborysa** [dotkom/onlineweb4#2189]
## What kind of an issue is this?
- Bug report

When not providing a quantity field (or names the quantity field wrongly) the api assumes the user only wants to buy one of the item.

## What is the expected behavior?
All the fields in the api should be required to be specified and the api should return an error when fields aren't specified.

## What is the current behavior?
Current behavior is that the api falls back to a default value of 1 for quantity.

**Comment by sklirg** [comment]
I would say that this is an error on the database/data validation layer, not necessarily in the API.

https://github.com/dotkom/onlineweb4/blob/68f54ed7bbaf258fd99de78ba922963a7785f8c2/apps/shop/models.py#L22

Relevant source code. I'd suggest removing the default value, which will fail to validate the request if the quantity value is missing, rather than automatically setting it to 1.

**Comment by FredrikAugust** [comment]
Completely agree with @sklirg. Although this relatively large fuck-up is clearly my fault it could have been avoided by simply throwing when no quantity field is provided. I also think this way of handling misformatted errors should be employed everywhere, and rather send back a 400 Bad Request.

**Comment by sklirg** [comment]
That's exactly how Django rest framework works if missing required
parameters 😉
