### ISSUE TITLE
ReferenceError: Urls is not defined when clicking on Online logo

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2242]
This has happened two times in Firefox 66.0 on Windows 10, see Sentry for more information

https://sentry.io/organizations/dotkom/issues/968331210/?project=204971&referrer=github_plugin

```
ReferenceError: Urls is not defined
  at modules (external "Urls":1:1)
  at __webpack_require__ (webpack/bootstrap 519b222291c20d2217fa:54:1)
  at modules (frontpage-519b222291c20d2217fa.js:304:63)
  at __webpack_require__ (webpack/bootstrap 519b222291c20d2217fa:54:1)
  at modules (frontpage-519b222291c20d2217fa.js:245:75)
...
(9 additional frame(s) were not displayed)
```

**Comment by oleast** [comment]
So this probably happens because of the Urls being loaded as a separate script to the main page and other scripts. It is imported into the other JS files as if it was a JS module, but it is actually just added to the global scope (I think?). If it is not added in time for the other scripts to run, all JS that uses it will break on load. Which means basically nothing important on the front-page will display.

You can test this out for yourselves by going to the `network` tab in dev tools and block the `/jsreverse/` endpoint.

I happens maybe a few times a year, and I don't know if we really care?
