### ISSUE TITLE
Migrate from unmaintained OIDC library (django-oidc-provider)

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2576]
As per https://github.com/juanifioren/django-oidc-provider/issues/377, `django-oidc-provider` is unmaintained and we should look into finding a replacement asap

**Comment by FluidSense** [comment]
Just waiting for this one since we already depend on it for oauth2 https://github.com/jazzband/django-oauth-toolkit/pull/915

**Comment by FluidSense** [comment]
_In progress_

### Critical tasks:
_These are the tasks that needs to be done before PR can be created_

- [ ] Allow `openid`-scope
- [ ] Get `id_token` as JWT  
- [ ] Check that existing scopes do not break
- [ ] Simplify existing scope names
- [ ] Add new scopes
- [ ] Readd extended Application Model 
- [ ] Add connected apps in `dump_data`
- [ ] Add connected apps for OWF-"Personvern"-view.
- [ ] Style authorization-page
- [ ] Replace DRF-endpoints for [Authentication Dashboard](https://github.com/dotkom/auth-board)
- [ ] Ensure that users can see currently active `refresh token`s and revoke them in case they are stolen.

### Descriptive tasks
_Various fields could be implemented for us admins to easier see what a client is used for_

- [ ] Add description as nullable field on Application model
- [ ] Add hosted website url


### Replacement tasks
_I suggest we give a week or two of migration period, where both `django-oidc-provider` and `django-oauth-toolkit` exists alongside each other so that people can update their applications_

- [ ] Remove endpoints for `django-oidc-provider`
- [ ] Remove `django-oidc-provider`-fields from `admin`
- [ ] Remove connected `django-oidc-provider`-apps from `dump-data`
- [ ] Remove connected `django-oidc-provider`-apps from OWF-"Personvern"-view.

**Comment by FluidSense** [comment]
## Changelog 🆕 

To easier write the e-mail to client owners, I will write down breaking changes here as I work.

### Scopes 🔭 
 - The scope `onlineweb4` is renamed. This scope used to add claims to /userinfo, with different information regarding your user, such as address, username, etc. This is renamed to `profile`. Please change to using `profile`.  
 
### URLs 💻 
 - Previous urls were prefixed with `openid/`. The new prefix is `sso/`.

**Comment by FluidSense** [comment]
#  Add connected apps for OWF-"Personvern"-view.

If I am correct, OWF calls on `api/v1/oidc/consent`, which is tightly coupled with `django-oidc-provider`.
I suggest having this as it's own issue over at OWF, and use the new endpoint there to combine the two.

**Comment by FluidSense** [comment]
# Checklist for internal applications which might need updated client information & endpoints

- [ ] OWF (certainly)
- [ ] Regme (possibly not)
- [ ] Nibble (certainly)
- [ ] SDF (possibly not)

**Comment by sklirg** [comment]
> 
> ## Checklist for internal applications which might need updated client information & endpoints
> *snip*
>     * [ ]  SDF (possibly not)

https://github.com/dotkom/super-duper-fiesta/blob/v2.0.5/server/auth/oidc.js#L35
