### ISSUE TITLE
Billed for wrong items in webshop

### ISSUE THREAD

**Issue by henrikskog** [dotkom/onlineweb4#2887]
**Describe the bug**
People are being billed for items not chosen when buying items. One of ways in which the bug can occur:  selecting an item, then unselecting it. If you then go to buy something else, you will also be billed for the item you selected then unselected. 

There has been multiple bug reports for this. This is the latest one:

“Heisann! Det kan virke som problemet med overbetaling om man fjerner en artikkel fra webshop-handlekurven fortsatt ikke er borte :sweat_smile: Er en som fjernet en sløyfe når vedkommende skulle kjøpe ølglass og ble alikevell fakturert for sløyfen i stripe, men registrert for kun ølglassene :see_no_evil:”

**To Reproduce**

**Expected behavior**
- Users should only be billed for the items that are in their cart when pressing buy!!

**Screenshots**

**Comment by marcelwk** [comment]
#### To reproduce
- Go to webshop and add two items into cart
- Remove one of them
- Check the active orderline (https://old.online.ntnu.no/api/v1/webshop/orderlines/)

Notice how `Orderline.subtotal` (which is shown in the UI) shows the price of the remaining item, while `Orderline.payment.payment_prices.price` (which is sent to Stripe) shows the price of both items.

Also, if you add a third item after the removal, both values become correct.

Seems like the issue is that the payment object is only updated when a new item is added, and not on removal.
